---
- name: Running the Photo ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/photos/'

    - name: Install photo packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - bt747  # getting files from GPS Logger's, https://wiki.openstreetmap.org/wiki/Holux_RCV-3000

    - name: Install AUR packages
      become: true
      become_method: sudo
      aur: name="{{item}}" tool=yaourt
      with_items:
        - darktable  # https://www.darktable.org

# TODO:
# * add following to this repo: `/root/.config/bt747/bt747settings.pdb`.
# * deploy the bt747 config file via ansible.
# * Write script to run `sudo bt747`, for port access. This should chmod/chown
#   all logger/gpx files on close, for non-root access.
