---
- name: Running the Photo ansible playbook...
  hosts: localhost
  tasks:
    - name: Install photo packages
      become: true
      become_method: sudo
      pacman:
        name:
          - bt747  # getting files from GPS Logger's, https://wiki.openstreetmap.org/wiki/Holux_RCV-3000
          - iscan  # Epson printer frontend. https://wiki.archlinux.org/index.php/SANE/Scanner-specific_problems#Epson
          - darktable  # https://www.darktable.org
          - krita  # https://krita.org/en
        state: latest

    - name: Install AUR packages
      # become: true
      # become_method: sudo
      aur: name="{{item}}" tool=yaourt
      with_items:
        - iscan-plugin-gt-f670  # Epson Perfection V200 Photo scanner support.

# TODO:
# * add following to this repo: `/root/.config/bt747/bt747settings.pdb`.
# * deploy the bt747 config file via ansible.
# * Write script to run `sudo bt747`, for port access. This should chmod/chown
#   all logger/gpx files on close, for non-root access.
