---
- name: Running the Photo ansible playbook...
  hosts: localhost
  tasks:
    - name: Install photo packages
      become: true
      become_method: sudo
      pacman:
        name:
          - bt747  # getting files from GPS Logger's, https://wiki.openstreetmap.org/wiki/Holux_RCV-3000
          - iscan  # Epson printer frontend. https://wiki.archlinux.org/index.php/SANE/Scanner-specific_problems#Epson
          - darktable  # https://www.darktable.org
          - krita  # https://krita.org/en
          - libwacom  # https://wiki.archlinux.org/title/Wacom_tablet
          - xf86-input-wacom  # https://wiki.archlinux.org/title/Wacom_tablet
          # - linux-headers  # https://wiki.archlinux.org/title/Wacom_tablet
        state: latest
      tags:
        - photos

    - name: Install AUR packages
      # become: true
      # become_method: sudo
      aur:
        use: yay
        name:
          - iscan-plugin-gt-f670  # Epson Perfection V200 Photo scanner support.

          # Huion tablet links:
          #
          # * https://wiki.archlinux.org/title/Wacom_tablet
          # * https://github.com/Mainman002/Linux-OpenTabletUI
          # * https://digimend.github.io/support/
          - digimend-kernel-drivers-dkms  # https://wiki.archlinux.org/title/Wacom_tablet
          # - digimend-kernel-drivers-dkms-git  # https://wiki.archlinux.org/title/Wacom_tablet
          - write_stylus  # http://www.styluslabs.com
      tags:
        - photos

    - name: Copy Huion Tablet script to /etc/X11/xorg.conf.d/
      become: true
      become_method: sudo
      copy:
        src: '{{playbook_dir}}/../bash/etc/X11/xorg.conf.d/50-tablet.conf'
        dest: /etc/X11/xorg.conf.d/
        owner: 'root'
        group: 'root'
        mode: 0644
      tags:
        - photos

# TODO:
# * add following to this repo: `/root/.config/bt747/bt747settings.pdb`.
# * deploy the bt747 config file via ansible.
# * Write script to run `sudo bt747`, for port access. This should chmod/chown
#   all logger/gpx files on close, for non-root access.
