---
# https://wiki.archlinux.org/index.php/Dell_XPS_13_(9370)
- name: Running the Dell XPS 13 ansible playbook...
  hosts: localhost
  tasks:
    - name: Install Dell packages
      become: true
      become_method: sudo
      pacman:
        name:
          # Was: https://wiki.archlinux.org/index.php/Touchpad_Synaptics
          # Now: https://wiki.archlinux.org/index.php/Libinput
          # Further settings in: /etc/X11/xorg.conf.d/30-touchpad.conf.
          - xf86-input-libinput  # xf86-input-synaptics is deprecated.
          # Dell BIOS updating = Download exe to a pendrive and using the Bios
          # Flash Update at boot time (F12), since I'm legacy (instead of UEFI).
          # www.dell.com/support/article/uk/en/ukdhs1/sln171755/updating-the-dell-bios-in-linux-and-ubuntu-environments?lang=en
          # Dell component FW updates:
          # https://wiki.archlinux.org/index.php/Flashing_BIOS_from_Linux#fwupd
          # https://fwupd.org/lvfs/device/7ceaf7a8-0611-4480-9e30-64d8de420c7c
          - fwupd
          # FIXME: need to make the following permanent for my Tandberg webcam:
          #  v4l2-ctl --set-fmt-video=width=1280,height=720,pixelformat=MJPG
          - v4l2ucp  # v4l configuration for webcams.
        state: latest

    - name: Copy logind.conf script to /etc/systemd/
      # NOTE: No longer need a custom `suspend-then-hibernate.service`, since
      # this is now baked into `systemd` from version 239. The default is 2hrs
      # in suspend. Also, the custom service was broken since official support
      # came in. Reference:
      #
      # * https://github.com/systemd/systemd/pull/8274
      # * https://wiki.archlinux.org/index.php/Power_management#Delayed_hibernation_service_file
      #
      # test via: `systemctl -o verbose suspend-then-hibernate`.
      become: true
      become_method: sudo
      copy:
        src: '{{playbook_dir}}/{{item}}'
        dest: /etc/systemd/
        owner: 'root'
        group: 'root'
        mode: 0644
      with_items:
        - logind.conf
        - sleep.conf

    - name: Restart logind service to enable suspend with delayed hibernate
      # See: https://wiki.archlinux.org/index.php/Power_management#ACPI_events.
      become: true
      become_method: sudo
      systemd:
        name: systemd-logind.service
        enabled: True
        state: restarted

    - name: Copy 30-touchpad.conf script to /etc/X11/xorg.conf.d/
      become: true
      become_method: sudo
      copy:
        src: '{{playbook_dir}}/30-touchpad.conf'
        dest: /etc/X11/xorg.conf.d/
        owner: 'root'
        group: 'root'
        mode: 0755

    - name: Copy blacklist.conf to /etc/modprobe.d/
      # Removing psmouse module, since it is deprecated by libinput
      # Verify by: `lsmod | grep psmouse`, being empty.
      become: true
      become_method: sudo
      copy:
        src: '{{playbook_dir}}/blacklist.conf'
        dest: /etc/modprobe.d/
        owner: 'root'
        group: 'root'
        mode: 0755

    - name: Copy 90-override.conf script to /etc/sysctl.d/, for an inotify fix
      # https://docs.syncthing.net/users/faq.html#inotify-limits
      become: true
      become_method: sudo
      copy:
        src: '{{playbook_dir}}/90-override.conf'
        dest: /etc/sysctl.d/
        owner: 'root'
        group: 'root'
        mode: 0755

    # TODO: script printer updating/configuration steps:
    # https://bbs.archlinux.org/viewtopic.php?id=201719
    # * Plugin update with: `hp-plugin`.
    # * Printer config with: `sudo hp-setup -i`.
