---
- name: Running the Dell XPS 13 ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/dell/'

    - name: Install Dell packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - xf86-input-synaptics

    # TODO: custom `/etc/systemd/logind.conf` for `hybrid-sleep`/`hibernate`.
    # See: https://wiki.archlinux.org/index.php/Power_management#ACPI_events.
