---
- name: Running the Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/'

    - name: Install remote working packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - mosh

    - name: Install generic programming packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - make

    - name: Install system-wide python packages
      become: true
      become_method: sudo
      pip:
        name: "{{item}}"
        state: latest
      with_items:
        - pep8
        - flake8
        - jedi
        - virtualenvwrapper
        - ipython
        - ipdb

    - name: Install C++ packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - cmake
        # - gcc
        - gcc-multilib  # build 32/64-bit packages. Conflicts with `gcc`.
        - gdb
        - clang

    - name: Install my github repos
      # Need to out of band, sort out the ssh keys to access github.
      git:
        repo: "{{item.repo}}"
        dest: "{{item.dest}}"
        accept_hostkey: yes
        update: no
      with_items:
        - {repo: 'git@github.com:jackson15j/presentations.git', dest:
          '~/github_repos/presentations/'}
        - {repo: 'git@github.com:jackson15j/dot_emacs.git', dest:
          '~/github_repos/dot_emacs/'}
        - {repo: 'git@github.com:jackson15j/dot_files.git', dest:
          '~/github_repos/dot_files/'}
        - {repo: 'git@github.com:jackson15j/jackson15j.github.io.git', dest:
          '~/github_repos/jackson15j.github.io/'}
        - {repo: 'git@github.com:jackson15j/cpp_random_projects_for_learning.git', dest:
          '~/github_repos/cpp_random_projects_for_learning/'}
        - {repo: 'git@github.com:jackson15j/unittest_helloworld.git', dest:
          '~/github_repos/unittest_helloworld/'}
        - {repo: 'git@github.com:jackson15j/docker-tox-pyenv-runner.git', dest:
          '~/github_repos/docker-tox-pyenv-runner/'}
        - {repo: 'git@github.com:jackson15j/GoldenCheetah.git', dest:
          '~/github_repos/GoldenCheetah/'}
        - {repo: 'git@github.com:jackson15j/reddit-mode.git', dest:
          '~/github_repos/reddit-mode/'}
        - {repo: 'git@github.com:jackson15j/android_test.git', dest:
          '~/github_repos/android_test/'}

