---
- name:  Update & upgrade pacman once at start of ansible
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - set_fact:
        ansible_python_interpreter: "{{ansible_python_interpreter}}"

    - name:
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        update_cache: yes
        upgrade: yes
