---
# FIXME: Learn and update with the `pipenv` workflow: https://github.com/pypa/pipenv
- name: Running the Landslide Virtualenv ansible playbook for presentation rendering...
  hosts: localhost
  tasks:
    - name: Creating landslide virtualenv
      pip:
        name: "{{item}}"
        virtualenv: ~/virt_envs/landslide
        virtualenv_command: pipenv
        state: latest
      with_items:
        - landslide
        - watchdog  # needed for the `--watch` for changes & regenerate slides option.
      tags:
        - virtualenvs
