---
- name: Running the Music ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path
      tags:
        - music

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/music/'
      tags:
        - music

    # Tasks to install Music packages for the configs like mpd/abcde.
    - name: Symlink music configs to user home directory
      file:
        src: '{{base_path}}{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes  # See: https://github.com/ansible/ansible/issues/7627
      with_items:
        - .mpdconf
        - .abcde.conf
      tags:
        - music

    - name: Install Music packages
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - mpd
        - abcde
        # TODO: double check mpd/abcde dependencies for flac/albumart...
      tags:
        - music

    - name: Remove the python2 version of eyeD3 installed by abcde
      become: true
      become_method: sudo
      pacman:
        name: eyeD3
        state: absent

    - name: Now lets install/upgrade the python3 version of eyeD3 from pip. Ideally should make an abcde virtualenv.
      become: true
      become_method: sudo
      pip:
        name: eyeD3
        state: latest
      tags:
        - music

    # FIXME: This might be first time only - investigate??
    # - name: Start MPD user service
    #   # wiki.archlinux.org/index.php/Music_Player_Daemon#Autostart_with_systemd
    #   # https://wiki.archlinux.org/index.php/Systemd/User
    #   shell: systemctl --user start mpd
