---
- name: Running the Music ansible playbook...
  hosts: localhost
  tasks:
    - name: Symlink music config directories to ~/.config/
      file:
        src: '{{playbook_dir}}/../bash/.config/{{item}}'
        dest: '~/.config/{{item}}'
        state: link
        force: yes
      with_items:
        - spotifyd
      tags:
        - music

    # Tasks to install Music packages for the configs like mpd/abcde.
    - name: Symlink music configs to user home directory
      file:
        src: '{{playbook_dir}}/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes  # See: https://github.com/ansible/ansible/issues/7627
      with_items:
        - .mpdconf
        - .abcde.conf
        - .mpd
      tags:
        - music

    # - name: Touch the local ~/Music/.mpd/mpd.log file
    #   # https://docs.ansible.com/ansible/latest/modules/file_module.html#file-module
    #   # Or a command example:
    #   # https://stackoverflow.com/questions/28347717/how-to-create-an-empty-file-with-ansible#34929776
    #   file:
    #     path: ~/Music/.mpd/mpd.log
    #     state: touch

    - name: Symlink .mpd directory to ~/Music/.mpd/
      file:
        src: '{{playbook_dir}}/.mpd'
        dest: ~/Music/.mpd
        state: link
        force: yes
      tags:
        - music

    # - name: Removing python3 eyeD3, since abcde installs a py2 version. Will fix this up in a later step.
    #   become: true
    #   become_method: sudo
    #   pip:
    #     name: eyeD3
    #     state: absent
    #   tags:
    #     - music

    - name: Install Music packages
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        name:
          - mpd
          - glyr  # Album art support for abcde
          - abcde
          - picard  # Musicbrainz tagger. Use to upload discid's if missing.
          - python-discid  # picard dependency for cd lookups. Haven't been able
                           # to get this to work from a virtualenv yet.
          - cantata
        state: latest
      tags:
        - music

    # - name: Remove the python2 version of eyeD3 installed by abcde
    #   become: true
    #   become_method: sudo
    #   pacman:
    #     name: python-eyed3
    #     state: absent
    #   tags:
    #     - music

    - name: Install abcde AUR dependencies and music packages
      aur: name="{{item}}" tool=yaourt update=yes
      with_items:
        # NOTE: Just found out that when a new version of Perl is installed, it
        # doesn't migrate modules to the latest versions folder
        # (`/usr/lib/perl5/5.XX/vendor_perl/<Package>/`). Do a pacman/yaourt
        # reinstall with `pacman -S <package>`.
        # eg: `yay -S --asdeps $(pacman -Qqo '/usr/lib/perl5/5.30')`. **and**
        # clean build the packages!!!
        - perl-musicbrainz-discid  # abcde dependency for MusicBrainz lookups.
        - perl-webservice-musicbrainz  # abcde dependency for MusicBrainz # lookups.
        - spotify
        - spotifyd  # https://github.com/Spotifyd/spotifyd
        - playerctl  # https://github.com/altdesktop/playerctl
        - spotify-tui  # https://github.com/Rigellute/spotify-tui.
        # TODO: Add spotifyd pulseaudio version.
        # TODO: Add: `~/.config/spotifyd/spotifyd.conf`.
        # TODO: Add: `systemctl --user enable/start spotifyd.service`.
        # https://github.com/Spotifyd/spotifyd
        # https://www.rockyourcode.com/spotify-in-the-terminal-with-spotify-tui-and-spotifyd/
      tags:
        - music

    # - name: Now lets install/upgrade the python3 version of eyeD3 from pip. Ideally should make an abcde virtualenv.
    #   become: true
    #   become_method: sudo
    #   pip:
    #     name: eyeD3
    #     state: latest
    #   tags:
    #     - music

    - name: Enable mpd service
      # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
      systemd:
        name: mpd.service
        enabled: True
        state: started
        scope: user
      tags:
        - music
