---
- name: Running the Music ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path
      tags:
        - music

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/music/'
      tags:
        - music

    # Tasks to install Music packages for the configs like mpd/abcde.
    - name: Symlink music configs to user home directory
      file:
        src: '{{base_path}}{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes  # See: https://github.com/ansible/ansible/issues/7627
      with_items:
        - .mpdconf
        - .abcde.conf
        - .mpd
      tags:
        - music

    - name: Symlink MPD playlists to ~/Music/.mpd/playlists
      file:
        src: '{{base_path}}.mpd/playlists'
        dest: ~/Music/.mpd/playlists
        state: link
        force: yes
      tags:
        - music

    - name: Removing python3 eyeD3, since abcde installs a py2 version. Will fix this up in a later step.
      become: true
      become_method: sudo
      pip:
        name: eyeD3
        state: absent
      tags:
        - music

    - name: Install Music packages
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - mpd
        - glyr  # Album art support for abcde
        - abcde
        - picard  # Musicbrainz tagger. Use to upload discid's if missing.
        - python-discid  # picard dependency for cd lookups. Haven't been able
                         # to get this to work from a virtualenv yet.
        - cantata
      tags:
        - music

    - name: Remove the python2 version of eyeD3 installed by abcde
      become: true
      become_method: sudo
      pacman:
        name: eyeD3
        state: absent
      tags:
        - music

    - name: Install abcde AUR depencies
      aur: name="{{item}}" tool=yaourt
      with_items:
        - perl-musicbrainz-discid  # abcde dependency for MusicBrainz lookups.
        - perl-webservice-musicbrainz  # abcde dependency for MusicBrainz lookups.
      tags:
        - music

    - name: Now lets install/upgrade the python3 version of eyeD3 from pip. Ideally should make an abcde virtualenv.
      become: true
      become_method: sudo
      pip:
        name: eyeD3
        state: latest
      tags:
        - music

    - name: Enable mpd service
      # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
      systemd:
        name: mpd.service
        enabled: True
        state: started
        user: yes
      tags:
        - music

    # - name: Create ~/Music/.mpd/
    #   file:
    #     path: ~/Music/.mpd/
    #     state: directory

    # - name: Touch the local ~/Music/.mpd/mpd.log file
    #   # https://docs.ansible.com/ansible/latest/modules/file_module.html#file-module
    #   # Or a command example:
    #   # https://stackoverflow.com/questions/28347717/how-to-create-an-empty-file-with-ansible#34929776
    #   file:
    #     path: ~/Music/.mpd/mpd.log
    #     state: touch
