---
- name: Running the gnome window manager ansible playbook...
  hosts: localhost
  tasks:
    - name: Apply Gnome touchpad settings
      # Gnome (Wayland) stamps over my xorg touch pad settings, so lets fix
      # them up.
      # FIXME: Can the xorg and Gnome settings be consolidated?
      dconf:
        key: "{{item.path}}"
        value: "{{item.value}}"
        state: present
      with_items:
        - {path: "/org/gnome/desktop/peripherals/touchpad/click-method",
           value: "'areas'"}
        - {path: "/org/gnome/desktop/peripherals/touchpad/edge-scrolling-enabled",
           value: "false"}
        - {path: "/org/gnome/desktop/peripherals/touchpad/natural-scroll",
           value: "false"}
        - {path: "/org/gnome/desktop/peripherals/touchpad/speed",
           value: "0.6"}
        - {path: "/org/gnome/desktop/peripherals/touchpad/tap-to-click",
           value: "true"}
        - {path: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled",
           value: "true"}
