- name: Running the C# Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Install C# packages
      become: true
      become_method: sudo
      pacman:
        name:
          - mono  # https://wiki.archlinux.org/index.php/Mono
          - mono-tools  # docs/testing
          - dotnet-sdk  # https://wiki.archlinux.org/index.php/.NET_Core
          - dotnet-runtime
        state: latest

    - name: Install C# AUR packages
      aur: name="{{item}}" tool=yaourt
      with_items:
        - monodevelop-stable  # MonoDevelop IDE.
