---
- name: Running the Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/'

    - name: Install remote working packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - mosh

    - name: Install generic programming packages
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - make
        #  Removed for: https://hub.docker.com/r/jagregory/pandoc/
        # - pandoc  # document file conversions.
        # - texlive-core  # PDF/Latex creation from pandoc. https://wiki.archlinux.org/index.php/TeX_Live
        - ruby  # docs.travis-ci.com/user/encryption-keys/

    - name: Install Travis CLI for the occassional CI task...
      # docs.travis-ci.com/user/encryption-keys/
      gem:
        name: travis
        state: latest
