- name: Running the GO Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Install GO packages
      become: true
      become_method: sudo
      pacman:
        name:
          - go
        state: latest

    - name: Install GO AUR packages
      aur: name="{{item}}" tool=yaourt
      with_items:
        - gopls  # https://github.com/golang/tools/tree/master/gopls
