- name: Running the Java Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Install Java packages.
      become: true
      become_method: sudo
      pacman:
        name:
          - jdk10-openjdk
          - openjdk10-doc
          - maven
        state: latest
