- name: Running the Productivity Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Install general productivity packages
      become: true
      become_method: sudo
      pacman:
        name:
          - libreoffice
          - peek  # screen recording to gif.
        state: latest
