- name: Running the Python Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    # - name: Install system-wide python packages
    #   become: true
    #   become_method: sudo
    #   pip:
    #     name:
    #       - pep8
    #       - flake8
    #       - jedi
    #       - pipenv  # replacement for virtualenv. See: https://docs.pipenv.org/install/
    #       - ipython
    #       - ipdb
    #     state: latest
    #   tags:
    #     - virtualenvs

    - name: Install system-wide python packages
      become: true
      become_method: sudo
      pacman:
        name:
          - python-pycodestyle  # rename for pep8.
          - flake8
          - python-jedi
          - python-pipenv  # replacement for virtualenv. See: https://docs.pipenv.org/install/
          - ipython
          - python-ipdb
        state: latest
      tags:
        - python
        - virtualenvs

    - name: Download latest poetry script.
      # https://python-poetry.org/docs/
      # curl -sSL https://install.python-poetry.org | python3 -
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
      get_url:
        url: https://install.python-poetry.org
        dest: /tmp/install-poetry.py
      tags:
        - poetry
        - python
        - virtualenvs

    - name: Install poetry system wide
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html
      ansible.builtin.shell: python /tmp/install-poetry.py
      tags:
        - poetry
        - python
        - virtualenvs
