- name: Running the Random Dev Environment ansible playbook...
  hosts: localhost
  tasks:
    - name: Install random stuff I am toying with, but are not core packages
      become: true
      become_method: sudo
      pacman:
        name:
          - rabbitmq
          - docker-compose
        state: latest
