---
- name: Running the Bash ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/bash/'

    - name: Set global git user name
      command: git config --global user.name "Craig Astill"

    - name: Set global git user email
      command: git config --global user.email "craigastill@gmail.com"

    - name: Symlink config files to user home directory
      file:
        src: '{{base_path}}{{item}}'
        dest: '~/{{item}}'
        state: link
        force: yes
      with_items:
        - .bashrc
        - .tmux.conf

    - name: Copy tmux_share script to /usr/local/bin for guest access.
      become: true
      become_method: sudo
      copy:
        src: '{{base_path}}tmux_share'
        dest: /usr/local/bin/
        owner: '{{ansible_user_id}}'
        group: '{{ansible_user_gid}}'
        mode: 0755

    - name: Install Bash packages
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - python-pip
        - tmux
        - syncthing  # https://wiki.archlinux.org/index.php/Syncthing.
        - powertop  # diagnose battery/power management issues.
        - jnettop  # A top-like console network traffic visualizer.
        # TODO scripting of grabbing a default smb config from somewhere to
        # `/etc/samba/smb.conf`.
        - samba  # https://wiki.archlinux.org/index.php/samba.
        - rdesktop
        - tigervnc  # binaries are `vncviewer`, `vncserver`, etc...
        - gvfs-afc  # IOS support in filemanger:
          # https://wiki.archlinux.org/index.php/IOS
        - ifuse  # IOS mounting support.
        - adobe-source-han-sans-jp-fonts  # Japanese font.

    - name: Enable SyncThing service
      # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
      systemd:
        name: syncthing.service
        enabled: True
        state: started
        user: yes

    - name: Create ~/Downloads/iphone for later manual ifuse mounting when plugged in.
      file:
        path: ~/Downloads/iphone
        state: directory
