---
- name: Running the Bash ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/bash/'

    - name: Set global git user name
      command: git config --global user.name "Craig Astill"

    - name: Set global git user email
      command: git config --global user.email "craigastill@gmail.com"

    - name: Symlink config files to user home directory
      file:
        src: '{{base_path}}{{item}}'
        dest: '~/{{item}}'
        state: link
        force: yes
      with_items:
        - .bashrc
        - .bash_prompt

    - name: Install Bash packages
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        name:
          - yaourt
          - python-pip
          - tmux
          - syncthing  # https://wiki.archlinux.org/index.php/Syncthing.
          - powertop  # diagnose battery/power management issues.
          - jnettop  # A top-like console network traffic visualizer.
          - iptraf-ng  # network traffic visualizer with wireshark scroll logs.
          # TODO scripting of grabbing a default smb config from somewhere to
          # `/etc/samba/smb.conf`.
          - samba  # https://wiki.archlinux.org/index.php/samba.
          - rdesktop
          - tigervnc  # binaries are `vncviewer`, `vncserver`, etc...
          - gvfs-afc  # IOS support in filemanger:
            # https://wiki.archlinux.org/index.php/IOS
          - ifuse  # IOS mounting support.
          - adobe-source-han-sans-jp-fonts  # Japanese font.
        state: latest

    - name: Explicitly remove tracker and all depenant packages
      # Removing `tracker` since I don't use it's features or most of the
      # programs that use it. Also tired of the noise in `journalctl` when I'm
      # investigating other issues.
      #
      # Using `Command` since the pacman module does not allow `-c` in:
      # `pacman -Rc <blah>`.
      #
      # For reference:
      #
      # $ sudo pacman -R tracker
      #   checking dependencies...
      #   error: failed to prepare transaction (could not satisfy dependencies)
      #   :: brasero: removing tracker breaks dependency 'tracker'
      #   :: gnome-online-miners: removing tracker breaks dependency 'tracker'
      #   :: grilo-plugins: removing tracker breaks dependency 'tracker'
      #   :: nautilus: removing tracker breaks dependency 'tracker'
      #   :: tracker-miners: removing tracker breaks dependency 'tracker'
      #
      # $ sudo pacman -Rc tracker
      # checking dependencies...
      # :: grilo optionally requires grilo-plugins: Plugins for grilo
      # :: totem optionally requires grilo-plugins: Media discovery
      #
      # Packages (11) antergos-gnome-meta-1.1-1  brasero-3.12.2-2
      # gnome-documents-3.28.1-1 gnome-music-1:3.28.2.1-1
      # gnome-online-miners-3.26.0-1 gnome-photos-3.28.0-3
      # gnome-tweaks-3.28.1-1 grilo-plugins-0.3.5+12+g7ecf4b2-1
      # nautilus-3.28.1-1 tracker-miners-2.0.5-1 tracker-2.0.4-1
      #
      # Total Removed Size:  50.47 MiB
      #
      # :: Do you want to remove these packages? [Y/n]
      become: true
      become_method: sudo
      command: pacman -Rc --noconfirm tracker
      # FIXME: write a better command if package is not present, instead of
      # ignoring.
      ignore_errors: yes
      tags:
        - remove

    - name: Enable SyncThing service
      # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
      systemd:
        name: syncthing.service
        enabled: True
        state: started
        scope: user

    - name: Create ~/Downloads/iphone for later manual ifuse mounting when plugged in.
      file:
        path: ~/Downloads/iphone
        state: directory

    - name: Copy smb.conf script to /etc/samba/
      become: true
      become_method: sudo
      copy:
        src: '{{base_path}}smb.conf'
        dest: /etc/samba/
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: Restart smb service.
      # See: https://wiki.archlinux.org/index.php/samba
      become: true
      become_method: sudo
      systemd:
        name: smb.service
        enabled: True
        state: restarted
