---
- name: Running the xfce4 window manager ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/bash/'

    - name: Symlink xfce4 directory to ~/.config/xfce4
      file:
        src: '{{base_path}}xfce4'
        dest: ~/.config/xfce4
        state: link
        force: yes

    - name: Install xfce4 packages and dependencies
      # https://wiki.archlinux.org/index.php/Xfce
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - xfce4
        - xfce4-goodies
        - blueman  # https://github.com/blueman-project/blueman, BT management.
        - redshift # https://wiki.archlinux.org/index.php/Redshift

    - name: Enable RedShift night temperature service
      systemd:
        name: redshift-gtk.service
        enabled: True
        state: started
        user: yes
