---
- name: Running the xfce4 window manager ansible playbook...
  hosts: localhost
  tasks:
    - name: Symlink xfce4 config directories to ~/.config/
      file:
        src: '{{playbook_dir}}/{{item}}'
        dest: '~/.config/{{item}}'
        state: link
        force: yes
      with_items:
        # FIXME: Commented out whilst I test out Manjaro (previously Antergos).
        # - xfce4
        - redshift

    - name: Install xfce4 packages and dependencies
      # https://wiki.archlinux.org/index.php/Xfce
      become: true
      become_method: sudo
      pacman:
        name:
          - redshift # https://wiki.archlinux.org/index.php/Redshift
          - arandr  # Easy tool to output xrandr displays.
          # FIXME: Commented out whilst I test out Manjaro (previously
          # Antergos).
          # - xfce4
          # - xfce4-goodies
          # - network-manager-applet  # Panel applet. TODO: find an xfce variant.
          # - blueman  # https://github.com/blueman-project/blueman, BT management.
          # - xreader  # PDF/document viewer alternative to gnome's `evince`.
          # - gnome-keyring  # Can't find a non-gnome variant.
          # - seahorse  # GUI to modify the keyring.
          # FIXME: put in work ansible. Along with #
          # /etc/NetworkManager/system-connections/<work-sstp-vpn>
          - network-manager-sstp
        state: latest

    - name: Remove bad xfce4 packages
      become: true
      become_method: sudo
      pacman:
        name:
          # `xflock4` is picking up `light-locker`, but it's a buggy and
          # unsupported package. Hence removal.
          - light-locker
        state: absent

    # - name: Install AUR packages
    #   aur: name="{{item}}" tool=yaourt
    #   with_items:
    #     # Fixes the issue of the Super (windows) key ignoring modifiers.
    #     # https://github.com/hanschen/ksuperkey,
    #     # https://forum.xfce.org/viewtopic.php?id=9643.
    #     # - ksuperkey
    #     # NOTE: Going with using `Super+space` for the whiskermenu to allow
    #     # modifiers to work. https://bugzilla.xfce.org/show_bug.cgi?id=7845.

    - name: Enable RedShift night temperature service
      systemd:
        name: redshift-gtk.service
        enabled: True
        state: started
        scope: user

    - name: Symlink .screenlayout directory to ~/.screenlayout
      # xfce is rubbish with hotplugging multiple displays. So lets use arandr
      # to quickly generate the xrandr line to fix this up with a script.
      # TODO: display detection to get our scripts called on hotplug.
      file:
        src: '{{playbook_dir}}/.screenlayout'
        dest: ~/.screenlayout
        state: link
        force: yes
