---
- name: Running the xfce4 window manager ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/bash/'

    - name: Install xfce4 packages and dependencies
      # https://wiki.archlinux.org/index.php/Xfce
      become: true
      become_method: sudo
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - xfce4
        - xfce4-goodies
