---
- name: Running the Web ansible playbook...
  hosts: localhost
  tasks:
    # - name: Get PGP key for discord's libc dependency
    #   # https://aur.archlinux.org/packages/libc%2B%2B/
    #   command: gpg --recv-keys 0FC3042E345AD05D

    - name: Install Web packages
      become: true
      become_method: sudo
      pacman:
        name:
          - firefox
        state: latest

    - name: Install AUR packages
      aur: name="{{item}}" tool=yaourt
      with_items:
        - opera
        - opera-ffmpeg-codecs
        - discord
        - google-chrome
        # - slack-desktop
        - teams
